version: '3'

services:
  web:
    build: ./
    command: bash -c "python manage.py collectstatic --no-input && gunicorn ipl.wsgi:application --bind 0.0.0.0:8000 -w 4"
    volumes:
      - /static:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ipl_usr
      - POSTGRES_PASSWORD=ipl_db__
      - POSTGRES_DB=ipl_db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - /static:/static
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
