# Generated by Django 2.2.7 on 2019-11-16 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('team1', models.CharField(default='', max_length=50)),
                ('team2', models.CharField(default='', max_length=50)),
                ('toss_winner', models.CharField(default='', max_length=50)),
                ('toss_decision', models.CharField(choices=[('bat', 'bat'), ('field', 'field')], max_length=50)),
                ('result', models.CharField(choices=[('no result', 'no result'), ('normal', 'normal'), ('tie', 'tie')], max_length=50)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(default='', max_length=50)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(default='', max_length=50)),
                ('venue', models.CharField(default='', max_length=250)),
                ('umpire1', models.CharField(default='', max_length=50)),
                ('umpire2', models.CharField(default='', max_length=50)),
                ('umpire3', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('batting_team', models.CharField(default='', max_length=50)),
                ('bowling_team', models.CharField(default='', max_length=50)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(default='', max_length=50)),
                ('non_striker', models.CharField(default='', max_length=50)),
                ('bowler', models.CharField(default='', max_length=50)),
                ('is_super_over', models.BooleanField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(default='', max_length=50)),
                ('dismissal_kind', models.CharField(default='', max_length=50)),
                ('fielder', models.CharField(default='', max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='season_stats.Match')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
